## Q1. How do you create a 2D Numpy array and calculate the sum of each row?

Answer. Creating a 2D NumPy array and calculating the sum of each row is straightforward and efficient with NumPy. Here's a step-by-step guide:

Step 1: Import NumPy
First, you need to import the NumPy library.

python
import numpy as np
Step 2: Create a 2D NumPy Array
You can create a 2D NumPy array using the np.array() function. For example, let's create a 2D array with some sample values:

python
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(array_2d)
Step 3: Calculate the Sum of Each Row
You can calculate the sum of each row using the np.sum() function and specifying the axis. For row-wise summation, the axis is 1.

python
row_sums = np.sum(array_2d, axis=1)
print("Sum of Each Row:")
print(row_sums)
Complete Example
Here’s the complete example, all together:

python
import numpy as np

# Step 1: Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(array_2d)

# Step 2: Calculate the sum of each row
row_sums = np.sum(array_2d, axis=1)
print("Sum of Each Row:")
print(row_sums)
Output
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of Each Row:
[ 6 15 24]
Explanation
np.array(): Creates a 2D array with the given values.

np.sum(): Calculates the sum of elements along the specified axis (1 for rows).

This simple process showcases how NumPy makes array operations both efficient and easy to implement. 


In [ ]:
Q2. write a pandas script to find the mean of a specific column in a dataframe.

Answer: Absolutely! Below is a script demonstrating how to calculate the mean of a specific column in a pandas DataFrame.

Example Script
python
import pandas as pd

# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}

# Creating a DataFrame
df = pd.DataFrame(data)

# Calculate the mean of the 'Age' column
mean_age = df['Age'].mean()

print(f"The mean age is: {mean_age}")
Explanation
Import pandas: The script starts by importing the pandas library.

Sample Data: A dictionary containing sample data is defined, including columns 'Name', 'Age', and 'Salary'.

Creating DataFrame: A DataFrame is created using the sample data.

Calculate Mean: The mean() function is used to calculate the mean of the 'Age' column.

Output: The mean value is printed.

Output
The mean age is: 32.5
This script is a simple yet powerful way to calculate the mean of a specific column in a pandas DataFrame.


In [ ]:
Q3. create a scatter plot using matplotlib.

Answer:Here’s an example of how you can create a scatter plot using Matplotlib in Python.

Example Script
python
import matplotlib.pyplot as plt

# Sample data
x = [1, 2, 3, 4, 5]
y = [2, 3, 5, 7, 11]

# Creating a scatter plot
plt.scatter(x, y, color='blue', marker='o')

# Adding titles and labels
plt.title('Sample Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Display the plot
plt.show()
Explanation
Import Matplotlib: The script starts by importing the pyplot module from Matplotlib.

Sample Data: Defines two lists, x and y, containing sample data points.

Scatter Plot: Uses plt.scatter() to create a scatter plot with the x and y data points. The color parameter sets the color of the points, and the marker parameter sets the shape of the points.

Titles and Labels: Adds a title to the plot and labels to the x-axis and y-axis using plt.title(), plt.xlabel(), and plt.ylabel().

Display: Displays the scatter plot using plt.show().

Output
When you run the script, you'll see a scatter plot with the specified data points, titles, and labels.
This is a simple yet effective way to visualize the relationship between two variables.


In [ ]:
Q4. How do you calculate the correlation matrix using seaborn and visualize it with a heatmap?

Answer:alculating the correlation matrix and visualizing it with a heatmap using Seaborn is a powerful way to understand the relationships between variables in your dataset.
Here's a step-by-step guide:

Step 1: Import Libraries
First, you need to import the necessary libraries.

python
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
Step 2: Load or Create Data
You can either load a dataset or create a sample DataFrame.

python
# Sample data
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 6, 7, 8, 9],
    'C': [9, 8, 7, 6, 5],
    'D': [2, 3, 4, 5, 6]
}
df = pd.DataFrame(data)
Step 3: Calculate the Correlation Matrix
Use the corr() method to calculate the correlation matrix.

python
correlation_matrix = df.corr()
print(correlation_matrix)
Step 4: Visualize with a Heatmap
Use Seaborn's heatmap() function to visualize the correlation matrix.

python
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix Heatmap')
plt.show()
Complete Example
Here’s the complete example all together:

python
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Sample data
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 6, 7, 8, 9],
    'C': [9, 8, 7, 6, 5],
    'D': [2, 3, 4, 5, 6]
}
df = pd.DataFrame(data)

# Calculate the correlation matrix
correlation_matrix = df.corr()
print("Correlation Matrix:\n", correlation_matrix)

# Visualize with a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix Heatmap')
plt.show()
Explanation
Import Libraries: Imports Seaborn, Matplotlib, and pandas.

Load/Create Data: Defines a sample DataFrame.

Calculate Correlation Matrix: Uses df.corr() to calculate the correlation matrix.

Visualize Heatmap: Uses Seaborn's heatmap() function to visualize the correlation matrix with annotations and a color map.

Benefits
Correlation Insight: The heatmap helps in quickly identifying the strength and direction of relationships between variables.

Visual Clarity: Color gradients make it easy to interpret the correlation values.

This approach allows you to effectively analyze and visualize the relationships between multiple variables in your dataset. 

In [ ]:
Q5. Generate a bar plot using plotly.

Answer:reating a bar plot using Plotly is a great way to visualize categorical data. Here's an example demonstrating how to create a bar plot with Plotly Express:

Example Script
python
import plotly.express as px

# Sample data
data = {
    'Category': ['A', 'B', 'C', 'D'],
    'Values': [10, 15, 7, 12]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Create a bar plot
fig = px.bar(df, x='Category', y='Values', title='Sample Bar Plot')

# Show the plot
fig.show()
Explanation
Import Plotly Express: The script starts by importing the plotly.express module.

Sample Data: Defines a dictionary containing sample data with categories and their corresponding values.

Create DataFrame: Converts the dictionary into a pandas DataFrame.

Create Bar Plot: Uses the px.bar() function to create a bar plot. The x parameter sets the categories, the y parameter sets the values, and the title parameter adds a title to the plot.

Show Plot: Displays the bar plot using fig.show().

Output
When you run the script, you'll see an interactive bar plot with the specified categories and values. This plot will include tooltips, and you can zoom, pan, and interact with it directly in your browser.

Benefits
Interactive: The bar plot created with Plotly is interactive, allowing for better data exploration.

Easy Customization: Plotly provides various options for customizing the plot, including colors, labels, and more.

This example demonstrates how easy it is to create and customize bar plots using Plotly.

In [ ]:
Q6. create a dataframe and add a new column based on an existing column.

Answer: Here’s an example of how you can create a DataFrame and add a new column based on an existing column using pandas.

Example Script
python
import pandas as pd

# Step 1: Create a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Step 2: Add a new column based on an existing column
# For example, let's create a new column 'Age_in_10_years' which adds 10 to the 'Age' column
df['Age_in_10_years'] = df['Age'] + 10
print("\nDataFrame with new column:")
print(df)
Explanation
Import pandas: The script starts by importing the pandas library.

Create DataFrame: A DataFrame df is created with sample data containing columns 'Name' and 'Age'.

Add New Column: A new column 'Age_in_10_years' is added to the DataFrame. This column is created by adding 10 to each value in the 'Age' column.

Output: The script prints the original DataFrame and the modified DataFrame with the new column.

Output
Original DataFrame:
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

DataFrame with new column:
      Name  Age  Age_in_10_years
0    Alice   25               35
1      Bob   30               40
2  Charlie   35               45
3    David   40               50
This script demonstrates how to create a DataFrame and add a new column based on the values of an existing column using pandas.


In [ ]:
Q7. write a program to perform element-wise-multiplication of two numpy arrays.

Anmswer: Here’s a Python program that demonstrates how to perform element-wise multiplication of two NumPy arrays.

Program
python
import numpy as np

# Create two sample NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Perform element-wise multiplication
result = array1 * array2

# Print the result
print("Array 1:", array1)
print("Array 2:", array2)
print("Element-wise multiplication result:", result)
Explanation
Import NumPy: The script starts by importing the NumPy library.

Create Arrays: Two sample NumPy arrays, array1 and array2, are created.

Element-wise Multiplication: The element-wise multiplication of the two arrays is performed using the * operator.

Print Result: The original arrays and the result of the element-wise multiplication are printed.

Output
Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]
Element-wise multiplication result: [5 8 9 8 5]
This simple program efficiently performs element-wise multiplication of two NumPy arrays and prints the results.

In [ ]:
Q8. create a line plot with multiple lines using matplotlib.

Answer:Here’s how you can create a line plot with multiple lines using Matplotlib in Python.

Example Script
python
import matplotlib.pyplot as plt

# Sample data
x = [1, 2, 3, 4, 5]
y1 = [2, 3, 5, 7, 11]
y2 = [1, 4, 6, 8, 10]
y3 = [3, 5, 7, 9, 12]

# Creating the line plot with multiple lines
plt.plot(x, y1, label='Line 1', color='blue', marker='o')
plt.plot(x, y2, label='Line 2', color='green', marker='s')
plt.plot(x, y3, label='Line 3', color='red', marker='^')

# Adding titles and labels
plt.title('Sample Line Plot with Multiple Lines')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Adding a legend
plt.legend()

# Display the plot
plt.show()
Explanation
Import Matplotlib: The script starts by importing the pyplot module from Matplotlib.

Sample Data: Defines lists x, y1, y2, and y3, containing sample data points for the x-axis and three different lines.

Plot Lines: Uses the plt.plot() function to plot three different lines on the same graph. Each line is given a unique label, color, and marker style.

Titles and Labels: Adds a title to the plot and labels to the x-axis and y-axis using plt.title(), plt.xlabel(), and plt.ylabel().

Legend: Adds a legend to the plot using plt.legend() to differentiate between the lines.

Display: Displays the line plot using plt.show().

Output
When you run the script, you'll see a line plot with three different lines, each with unique markers and colors. The plot will also have titles, axis labels, and a legend to indicate which line is which. This is a clear and effective way to compare multiple sets of data on the same graph.

 

In [ ]:
Q9. Generate a pandas dataframe and filter rows where a column value is greter than a threshold.

Answer: Here’s a Python script to generate a pandas DataFrame and filter rows where the value in a specific column is greater than a given threshold.

Example Script
python
import pandas as pd

# Step 1: Create a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Step 2: Set the threshold value
threshold = 30

# Step 3: Filter rows where the 'Age' column is greater than the threshold
filtered_df = df[df['Age'] > threshold]
print("\nFiltered DataFrame (Age > 30):")
print(filtered_df)
Explanation
Import pandas: The script starts by importing the pandas library.

Create DataFrame: A DataFrame df is created with sample data containing columns 'Name', 'Age', and 'Salary'.

Set Threshold: The threshold value is set to 30.

Filter Rows: The DataFrame is filtered to include only rows where the 'Age' column value is greater than the threshold. This is done using boolean indexing.

Output: The script prints the original DataFrame and the filtered DataFrame.

Output
Original DataFrame:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000

Filtered DataFrame (Age > 30):
      Name  Age  Salary
2  Charlie   35   70000
3    David   40   80000
This script demonstrates how to generate a DataFrame and filter rows based on a column value using pandas.


In [ ]:
Q10. create a histogram using seaborn to visualise a distribution.

Answer: Creating a histogram using Seaborn is a great way to visualize the distribution of a dataset. Here’s an example demonstrating how to do this:

Example Script
python
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Sample data
data = {
    'Age': [25, 30, 35, 40, 45, 25, 30, 35, 40, 45, 50, 55, 60]
}
df = pd.DataFrame(data)

# Create a histogram to visualize the distribution of 'Age'
sns.histplot(df['Age'], bins=10, kde=True)

# Adding titles and labels
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')

# Show the plot
plt.show()
Explanation
Import Libraries: The script starts by importing the necessary libraries—Seaborn, Matplotlib, and pandas.

Sample Data: Defines a dictionary with sample data for the 'Age' column and converts it into a pandas DataFrame.

Create Histogram: Uses Seaborn’s histplot() function to create a histogram of the 'Age' column.
    The bins parameter sets the number of bins, and the kde parameter adds a kernel density estimate to the plot.

Titles and Labels: Adds a title to the plot and labels to the x-axis and y-axis using plt.title(), plt.xlabel(), and plt.ylabel().

Show Plot: Displays the histogram using plt.show().

Output
When you run the script, you'll see a histogram displaying the distribution of ages in the sample dataset, complete with a smooth density curve overlay. This visualization helps you understand the frequency and distribution of the 'Age' values in your data.

In [ ]:
Q11. perform matrix multiplication using numpy.

Answer: Performing matrix multiplication using NumPy is straightforward and efficient. Here’s how you can do it:

Example Script
python
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

# Print the result
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of Matrix Multiplication:")
print(result)
Explanation
Import NumPy: The script starts by importing the NumPy library.

Create Matrices: Two matrices, matrix1 and matrix2, are created using the np.array() function.

Matrix Multiplication: The np.dot() function is used to perform matrix multiplication.

Print Results: The original matrices and the result of the matrix multiplication are printed.

Output
Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix Multiplication:
[[ 58  64]
 [139 154]]
In this example:

matrix1 is a 2x3 matrix.

matrix2 is a 3x2 matrix.

The resulting matrix, result, is a 2x2 matrix obtained by multiplying matrix1 and matrix2.

This demonstrates how NumPy makes matrix operations both powerful and easy to implement. 

In [ ]:
Q12. use pandas to load a csv file and display its first 5 rows.

Answer: Here’s an example of how you can use pandas to load a CSV file and display its first 5 rows.

Example Script
python
import pandas as pd

# Load the CSV file
df = pd.read_csv('path/to/your/file.csv')

# Display the first 5 rows
print(df.head())
Explanation
Import pandas: The script starts by importing the pandas library.

Load CSV: Uses the pd.read_csv() function to load the CSV file. Replace 'path/to/your/file.csv' with the actual path to your CSV file.

Display First 5 Rows: Uses the head() method to display the first 5 rows of the DataFrame.

Output
Running this script will print the first 5 rows of the loaded CSV file, giving you a quick look at the data.


In [ ]:
Q13. create a 3D plot using plotly.

Answer: Creating a 3D plot using Plotly is a fantastic way to visualize data in three dimensions. Here's a step-by-step example demonstrating how to create a 3D scatter plot with Plotly Express:

Example Script
python
import plotly.express as px
import pandas as pd

# Sample data
data = {
    'X': [1, 2, 3, 4, 5],
    'Y': [2, 3, 5, 7, 11],
    'Z': [5, 6, 7, 8, 9],
    'Category': ['A', 'B', 'A', 'B', 'A']
}

# Create a DataFrame
df = pd.DataFrame(data)

# Create a 3D scatter plot
fig = px.scatter_3d(df, x='X', y='Y', z='Z', color='Category', title='3D Scatter Plot')

# Show the plot
fig.show()
Explanation
Import Plotly Express and pandas: The script starts by importing the necessary libraries.

Sample Data: Defines a dictionary with sample data for the 'X', 'Y', 'Z' coordinates and 'Category' for color coding.

Create DataFrame: Converts the dictionary into a pandas DataFrame.

Create 3D Scatter Plot: Uses the px.scatter_3d() function to create a 3D scatter plot. The x, y, and z parameters define the coordinates, and the color parameter distinguishes points by category.

Show Plot: Displays the 3D scatter plot using fig.show().

Output
When you run the script, you'll see an interactive 3D scatter plot with the specified data points, complete with color coding for categories and a title. This plot allows you to rotate, zoom, and explore the data in three dimensions.

Feel free to experiment with different datasets and customization options to create your own unique 3D visualizations.